# Generated by Django 4.2.6 on 2023-10-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight0',
            new_name='Flight1',
        ),
    ]
